version: '3'

services:
  sherlock-backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        GIT_TOKEN: ${GIT_TOKEN}
    container_name: sherlock-backend-ai
    ports:
      - "8000:8000"
    restart: unless-stopped
    privileged: true  # Be cautious with this in production